name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * *'

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dependency Review
        uses: github/dependency-review-action@v2
        with:
          manifest-path: 'requirements.txt'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Black Check
        run: |
          pip install black
          black --check .

      - name: Pylint
        run: |
          pip install pylint
          pylint digimapas backend memoria_vetorial

      - name: Bandit Scan
        run: |
          pip install bandit
          bandit -r digimapas -ll

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: CodeQL init
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Snyk Test
        uses: snyk/actions/python@master
        with:
          command: test

      - name: Labeler
        uses: actions/labeler@v4

      - name: Stale
        uses: actions/stale@v6
        with:
          stale-issue-message: 'Este issue está inativo. Comente para reabrir.'
          days-before-stale: 30
          days-before-close: 7

      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.15.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          required_contexts: ci-tests

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            - @semantic-release/changelog
            - @semantic-release/git
